version: '3'

services:
  gitlab-feishu-webhook:
    build:
      context: .
    image: gitlab-feishu-webhook
    container_name: gitlab-feishu-webhook
    restart: always
    environment:
      - GIN_MODE=release
      - FEISHU_BOT_WEBHOOK_URL=YOU_FEISHU_BOT_WEBHOOK_URL
    ports:
      - "8083:8083"